export const MOODS = {
  happy: {
    label: 'Happy',
    icon: '☀️',
    query: 'Phonk',
    gradient: 'from-yellow-400 to-orange-400',
    bg: 'bg-yellow-500/10',
    accent: 'text-yellow-400',
    border: 'border-yellow-500/30 hover:border-yellow-400',
    ring: 'ring-yellow-400/50',
  },
  sad: {
    label: 'Sad',
    icon: '🌧️',
    query: 'Mr siro',
    gradient: 'from-blue-400 to-indigo-500',
    bg: 'bg-blue-500/10',
    accent: 'text-blue-400',
    border: 'border-blue-500/30 hover:border-blue-400',
    ring: 'ring-blue-400/50',
  },
  focused: {
    label: 'Focused',
    icon: '🎯',
    query: 'focus instrumental lofi study',
    gradient: 'from-purple-400 to-violet-500',
    bg: 'bg-purple-500/10',
    accent: 'text-purple-400',
    border: 'border-purple-500/30 hover:border-purple-400',
    ring: 'ring-purple-400/50',
  },
  relax: {
    label: 'Relax',
    icon: '🌊',
    query: 'EDM tiktok',
    gradient: 'from-teal-400 to-cyan-500',
    bg: 'bg-teal-500/10',
    accent: 'text-teal-400',
    border: 'border-teal-500/30 hover:border-teal-400',
    ring: 'ring-teal-400/50',
  },
}
